site_name: Tridev
theme:
  name: material
  logo: assets/lakitu.svg
  favicon: assets/lakitu.svg
  palette:
    primary: red
  font:
    text: Roboto Slab
repo_url: https://github.com/dexcom-inc/platform-toolbox
repo_name: dexcom-inc/platform-toolbox
edit_uri: edit/main/tridev/docs
plugins:
  - search
  - mermaid2
  - awesome-pages
markdown_extensions:
  - admonition
nav:
  - Home: README.md
  - Quickstart: quickstart/quickstart.md
  - Helm:
    - Building a Helm Chart: helm/building-helm-chart.md
    - Tips and Tricks: helm/tips-and-tricks.md
  - FAQ: faq/faq.md
  - Charts:
    - cloudeng-deployment: charts/cloudeng-deployment.md
