name: mkdoc
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs requirements
        run: pip install -r requirements.txt
        working-directory: tridev/docs
      - name: Publish documentation to gh-pages branch
        run: mkdocs gh-deploy --force
        working-directory: tridev
